services:
  app:
    container_name: management-api
    platform: linux/x86_64
    depends_on:
      - mysql
    build: ./api
    ports:
      - 3333:3333
    command: ["npm", "run", "dev"]
    networks:
      - internal
  mysql:
    container_name: managementdb-mysql
    restart: always
    image: mysql:latest
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: managementdb
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "admin"
      MYSQL_PASS: "password"
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - internal
networks:
  internal:
    driver: bridge
