services:
  mysql:
    container_name: managementdb-mysql
    restart: always
    image: mysql:latest
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: managementdb
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'admin'
      MYSQL_PASS: 'password'
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - internal
networks:
  internal:
    driver: bridge